### ISSUE TITLE
对 更新于“时间” 的疑问

### ISSUE THREAD

**Issue by gaoming714** [Prodesire/prodesire.github.io#15]
文章以这样的信息开头，其中更新于的时间目前是repo的最后一次commit的时间（我看了几篇都是同一个时间，所以这么猜测），我个人感觉这个应该是这个文章相关commit的时间，似乎更合理。
 发表于 2019-11-25 | 更新于 2020-01-05 | 分类于 Python ， 命令行 | 评论数： 0 | 阅读次数： 25

**Comment by Prodesire** [comment]
> 文章以这样的信息开头，其中更新于的时间目前是repo的最后一次commit的时间（我看了几篇都是同一个时间，所以这么猜测），我个人感觉这个应该是这个文章相关commit的时间，似乎更合理。
> 发表于 2019-11-25 | 更新于 2020-01-05 | 分类于 Python ， 命令行 | 评论数： 0 | 阅读次数： 25

其实更新时间确实是文章相关commit的时间。
之所以看到几篇文章都有相同的更新时间，是因为我每一次都会批量修改命令行系列文章中最后一个章节的内容（也就是“相关文章”章节里要新增新文章的链接）~
