### ISSUE TITLE
开始写博客啦~ | Prodesire

### ISSUE THREAD

**Issue by Prodesire** [Prodesire/prodesire.github.io#2]
http://prodesire.cn/2018/12/29/%E5%BC%80%E5%A7%8B%E5%86%99%E5%8D%9A%E5%AE%A2%E5%95%A6/ 

 Prodesire 的博客

**Comment by Prodesire** [comment]
欢迎留言~

**Comment by istommao** [comment]
> @Prodesire
> 欢迎留言~

哈哈 老王终于开博了

**Comment by Prodesire** [comment]
> @istommao
> > @Prodesire
> > 欢迎留言~
> 
> 哈哈 老王终于开博了

嘿嘿，友链互相搞起来！

**Comment by istommao** [comment]
哈哈没问题

**Comment by longqzh** [comment]
很有技术含量! 支持支持!
