### ISSUE TITLE
如何加密你的 Python 代码 —— 记 PyCon China 2018 的一次分享 | Prodesire

### ISSUE THREAD

**Issue by Prodesire** [Prodesire/prodesire.github.io#5]
http://prodesire.cn/2019/01/06/%E5%A6%82%E4%BD%95%E5%8A%A0%E5%AF%86%E4%BD%A0%E7%9A%84-Python-%E4%BB%A3%E7%A0%81-%E2%80%94%E2%80%94-%E8%AE%B0-PyCon-China-2018-%E7%9A%84%E4%B8%80%E6%AC%A1%E5%88%86%E4%BA%AB/ 

 前言去年11月在PyCon China 2018 杭州站分享了 Python 源码加密，讲述了如何通过修改 Python 解释器达到加解密 Python 代码的目的。然而因为笔者拖延症发作，一直没有及时整理成文字版，现在终于战胜了它，才有了本文。 本文将首先介绍下现有源码加密方案的思路、方法、优点与不足，进而介绍如何通过定制 Python 解释器来达到更好地加解密源码的目的。 现有加密方案由于 P

**Comment by Prodesire** [comment]
> @longqzh
> 感谢共享修改解释器的方法，很新颖。
> 我个人还构想了一个方法(尚未验证): 发布给用户的程序缺少关键的部分，在实际功能运行之前须从服务器上下载pickle格式的函数或类; 下载时服务器就能判断客户端是否为正版等等。

这种方式在商业环境可能行不通，因为客户通常是在内网（且和外网互不联通）部署程序的

**Comment by longqzh** [comment]
> @Prodesire
> > @longqzh
> > 感谢共享修改解释器的方法，很新颖。
> > 我个人还构想了一个方法(尚未验证): 发布给用户的程序缺少关键的部分，在实际功能运行之前须从服务器上下载pickle格式的函数或类; 下载时服务器就能判断客户端是否为正版等等。
> 
> 这种方式在商业环境可能行不通，因为客户通常是在内网（且和外网互不联通）部署程序的

没错，我没有考虑内网的情况~ 呵呵
